version: "3.8"
volumes:
    db-store:
    vendor-store:
    node_modules-store:
services:
    app:
        build: ./infra/php
        volumes:
            - ./backend:/work
            - vendor-store:/work/vendor
    
    web:
        image: nginx:1.18-alpine
        ports:
            - 10081:80
        volumes:
            - ./backend:/work
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - node_modules-store:/work/backend/node_modules
        working_dir: /work

    db:
        build: ./infra/mysql
        volumes:
            - db-store:/var/lib/mysql